export const Action = (type, data) => ({ type, data });

export const MENU_DRAWER_CLICK = 'MENU_DRAWER_CLICK';
export const SORT_TABLE = 'SORT_TABLE';
export const ETABLISSEMENT_FORM_CHANGE = 'ETABLISSEMENT_FORM_CHANGE';
export const LOGIN_FORM_CHANGE = 'LOGIN_FORM_CHANGE';
export const ETABLISSEMENT_CLOSE_MODAL = 'ETABLISSEMENT_CLOSE_MODAL';
export const ETABLISSEMENT_OPEN_MODAL = 'ETABLISSEMENT_OPEN_MODAL';
export const SUBMIT_NEW_ETABLISSEMENT = 'SUBMIT_NEW_ETABLISSEMENT';
export const ETABLISSEMENT_DELETE = 'ETABLISSEMENT_DELETE';
export const SNACKBAR_DISPATCH = 'SNACKBAR_DISPATCH';
export const SNACKBAR_CLOSE = 'SNACKBAR_CLOSE';
export const FETCH = 'FETCH';
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
